apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-ohhb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:c6552302c8e875c3cd55578bd50247bc2437722563df7d0054f7558488cf57b0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
